version: '3.3'
services:
  mongo:
    ports:
      - '27017:27017'
    volumes:
      - ./mongodb:/home
    container_name: hongwei-mongo
    restart: always
    logging:
      options:
        max-size: 1g
    environment:
      - MONGO_INITDB_DATABASE=mydatabase
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    image: mongo
